
BINS=encoder.elf 
OBJS=../avr_common/uart.o
HEADERS=../avr_common/uart.h

# the file below contains the actual rules

include ../avr_common/avr.mk

# !!!!!!!!!!!!!!!! MODIFY HERE !!!!!!!!!!!!!!!! 



